[30-Jul-2018 15:12:51 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 15:12:51 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 15:12:51 UTC] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 15:18:37 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 15:18:37 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 15:18:37 UTC] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:35:07 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:35:07 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:35:07 UTC] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/opt/cpanel/ea-php71/root/usr/share/pear') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:18 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:18 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:18 UTC] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:19 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:19 UTC] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 16:36:19 UTC] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 11:36:38 America/Chicago] PHP Warning:  require(/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 11:36:38 America/Chicago] PHP Fatal error:  require(): Failed opening required '/home/revistag/dev.revistagestion.ec/vendor/symfony/var-dumper/Resources/functions/dump.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/revistag/dev.revistagestion.ec/vendor/composer/autoload_real.php on line 55
[30-Jul-2018 20:59:10 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[30-Jul-2018 20:59:10 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[30-Jul-2018 22:53:26 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[30-Jul-2018 22:53:36 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[30-Jul-2018 22:53:41 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[30-Jul-2018 22:53:42 UTC] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'revistag_dba'@'localhost' (using password: YES) in /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(142): PDO->__construct('mysql:host=loca...', 'revistag_dba', 'Revistagestion2...', Array)
#1 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(376): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/Database/Database.php(166): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(264): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(508): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(860): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/revistag/dev.revistagestion.ec/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\Core\DrupalKernel->boot()
#13 /home/revistag/dev.revistagestion.ec/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
